### ISSUE TITLE
Documentation still mentions generic pool 

### ISSUE THREAD

**Issue by elhigu** [knex/documentation#109]
The doc is not updated here: http://knexjs.org/#Installation-pooling

Should be fixed to refer tarn.

Original Issue: https://github.com/tgriesser/knex/pull/2450#issuecomment-383505845

**Comment by trentstollery** [comment]
Hey guys, Since the doc hasn't been updated I'm a little lost as to how the validate method now works with tarn.
Do you have any examples of how to setup a validate method in my knex config for a connection before it's borrowed from the pool? Does knex already do this? 
I would prefer to be able to setup my own just so I know what's going on but just looking for some examples as it doesn't seem to work the same way as the tarn config.

**Comment by elhigu** [comment]
Knex sets internally its own validate functions.

**Comment by trentstollery** [comment]
Thanks,
Yes I was aware of that but is it documented how these work?
We are having issues with knex not working correctly with our other db pool software, which we require and it seems to not be validating connections before it borrows them.
What I would like to be able to do is set a validation function like SELECT 1, to confirm the connection is active. However if knex is already doing that then we will look elsewhere for the issue.

**Comment by elhigu** [comment]
Knex's internal validation functions just check if connection is in disposed state or not. Sending always test query when checking connection out from pool would be way too much overhead. Also even after test query nothing would guarantee that connection is ok one millisecond afterwards.

**Comment by kibertoad** [comment]
First point was already addressed: https://github.com/knex/documentation/commit/75d0fce4e87e61b89eaef278d44973eac0020f16

Could you provide a PR for the remaining part?

**Comment by erothmayer** [comment]
@kibertoad thanks for the pointer! Not sure what your release process is, but that commit was 13 days ago and the public website still shows the incorrect reference to generic-pool: https://knexjs.org/#Installation-pooling

Will see what I can do in terms of a PR for the additional docs. Before I start, are there any concerns around documenting `__knex__disposed` publicly? I was unclear whether the above would be viewed as an acceptable dependency to take on what looks like an internal flag, vs. potentially needing code changes to solidify the interface.

**Comment by kibertoad** [comment]
If I'm not mistaken, the plan is to regenerate documentation after 0.16.x is released.
I think that it makes sense to document __knex__disposed in the context of error handling, given that despite all the latest efforts to improve error handling, there are definitely some gaps remaining, and DIY would definitely help.
